# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/prana/Documents/Projects/FPGA-Soc/riscv/riscv.srcs/sources_1/ip/instr_mem/instr_mem.xci
# IP: The module: 'instr_mem' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/prana/Documents/Projects/FPGA-Soc/riscv/riscv.srcs/sources_1/ip/instr_mem/instr_mem_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'instr_mem'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/prana/Documents/Projects/FPGA-Soc/riscv/riscv.srcs/sources_1/ip/instr_mem/instr_mem.xci
# IP: The module: 'instr_mem' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/prana/Documents/Projects/FPGA-Soc/riscv/riscv.srcs/sources_1/ip/instr_mem/instr_mem_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'instr_mem'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
